version: "1.0"

services:

  mysql:
    image: mysql:8.0.26
    container_name: database-mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    ports:
    - 3307:3306
    - 33061:33060
    networks:
    - td2023  

networks:
  td2023:
    name: ms-unu

